name: MaintainableCSS - un enfoque para escribir CSS modular, escalable y mantenible | por Adam Silver
markdown: kramdown
url: https://maintainablecss.es
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: MaintainableCSS un enfoque para escribir CSS modular, escalable y mantenible.
